server:
  port: 9090

spring:
  h2:
    console:
      enabled: true

keycloak:
  realm: demo
  auth-server-url: http://localhost:8080/auth
  resource: springboot-keycloak
  public-client: true
  bearer-only: true